<x-app-layout>
<x-slot name="header"><div><h1 class="text-xl font-bold text-gray-900">Audit Logs</h1><p class="mt-1 text-sm text-gray-500">Review important actions performed throughout the system.</p></div></x-slot>
<div class="space-y-6">
<form method="GET" class="grid gap-3 rounded-2xl border border-gray-200 bg-white p-5 shadow-sm md:grid-cols-2 xl:grid-cols-6">
<input name="search" value="{{ request('search') }}" placeholder="Search activity..." class="rounded-xl border-gray-300 xl:col-span-2">
<select name="module" class="rounded-xl border-gray-300"><option value="">All modules</option>@foreach($modules as $module)<option value="{{ $module }}" @selected(request('module')===$module)>{{ ucfirst($module) }}</option>@endforeach</select>
<select name="user_id" class="rounded-xl border-gray-300"><option value="">All users</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected((string)request('user_id')===(string)$user->id)>{{ $user->full_name }}</option>@endforeach</select>
<input type="date" name="from" value="{{ request('from') }}" class="rounded-xl border-gray-300"><input type="date" name="to" value="{{ request('to') }}" class="rounded-xl border-gray-300">
<div class="flex flex-wrap gap-2 xl:col-span-6"><button class="rounded-xl bg-green-700 px-5 py-2.5 text-sm font-semibold text-white">Apply Filters</button><a href="{{ route('audit-logs.index') }}" class="rounded-xl border border-gray-300 px-5 py-2.5 text-sm font-semibold text-gray-700">Reset</a>@can('export activity logs')<a href="{{ route('audit-logs.export.csv', request()->query()) }}" class="rounded-xl border border-green-700 px-5 py-2.5 text-sm font-semibold text-green-700">Export CSV</a><a href="{{ route('audit-logs.export.pdf', request()->query()) }}" class="rounded-xl bg-red-600 px-5 py-2.5 text-sm font-semibold text-white">Generate PDF</a>@endcan</div>
</form>
<section class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div class="overflow-x-auto"><table class="min-w-full text-sm"><thead class="bg-gray-50 text-left text-xs uppercase text-gray-500"><tr><th class="px-5 py-3">Date</th><th class="px-5 py-3">User</th><th class="px-5 py-3">Module</th><th class="px-5 py-3">Action</th><th class="px-5 py-3">Description</th><th class="px-5 py-3">IP</th></tr></thead><tbody class="divide-y">@forelse($logs as $log)<tr><td class="whitespace-nowrap px-5 py-4">{{ $log->created_at->format('M d, Y h:i A') }}</td><td class="px-5 py-4"><div class="font-semibold text-gray-900">{{ $log->user?->full_name ?? 'System' }}</div><div class="text-xs text-gray-500">{{ $log->user?->getRoleNames()->join(', ') }}</div></td><td class="px-5 py-4 capitalize">{{ $log->module }}</td><td class="px-5 py-4"><span class="rounded-full bg-green-50 px-2.5 py-1 text-xs font-semibold uppercase text-green-700">{{ str_replace('-', ' ', $log->action) }}</span></td><td class="min-w-[280px] px-5 py-4 text-gray-600">{{ $log->description }}</td><td class="whitespace-nowrap px-5 py-4 text-gray-500">{{ $log->ip_address }}</td></tr>@empty<tr><td colspan="6" class="px-5 py-12 text-center text-gray-500">No audit activity matches your filters.</td></tr>@endforelse</tbody></table></div>@if($logs->hasPages())<div class="border-t px-5 py-4">{{ $logs->links() }}</div>@endif</section>
</div></x-app-layout>
