<x-app-layout>
    <x-slot name="header"><div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-sm font-medium text-green-700">Inventory Management</p><h2 class="text-2xl font-bold text-gray-900">Equipment Units</h2></div><div class="flex gap-2"><a href="{{ route('item-units.lookup') }}" class="rounded-xl border border-green-700 px-4 py-2.5 font-semibold text-green-700">Scan / Lookup</a>@can('restore items')<a href="{{ route('item-units.archived') }}" class="rounded-xl border border-gray-300 px-4 py-2.5 font-semibold text-gray-700">Archived</a>@endcan</div></div></x-slot>
    <div class="space-y-6">
        <div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach([['Total Units',$summary['total']],['Available',$summary['available']],['Borrowed',$summary['borrowed']],['Needs Attention',$summary['attention']]] as [$label,$value])<div class="rounded-2xl border border-gray-200 bg-white p-5 shadow-sm"><p class="text-sm font-medium text-gray-500">{{ $label }}</p><p class="mt-2 text-3xl font-bold text-gray-900">{{ number_format($value) }}</p></div>@endforeach</div>
        @if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 p-4 text-green-800">{{ session('success') }}</div>@endif
        @if(session('error'))<div class="rounded-xl border border-red-200 bg-red-50 p-4 text-red-800">{{ session('error') }}</div>@endif
        <form class="grid gap-3 rounded-2xl border border-gray-200 bg-white p-4 shadow-sm md:grid-cols-5">
            <input name="search" value="{{ $search }}" placeholder="Asset, barcode, serial, item..." class="rounded-xl border-gray-300 md:col-span-2">
            <select name="item" class="rounded-xl border-gray-300"><option value="">All items</option>@foreach($items as $item)<option value="{{ $item->id }}" @selected($itemId===$item->id)>{{ $item->item_code }} — {{ $item->name }}</option>@endforeach</select>
            <select name="status" class="rounded-xl border-gray-300"><option value="">All statuses</option>@foreach(['available','reserved','borrowed','maintenance','lost'] as $v)<option value="{{ $v }}" @selected($status===$v)>{{ ucfirst($v) }}</option>@endforeach</select>
            <div class="flex gap-2"><button class="flex-1 rounded-xl bg-green-700 px-4 py-2 font-semibold text-white">Filter</button><a href="{{ route('item-units.index') }}" class="rounded-xl border border-gray-300 px-4 py-2">Reset</a></div>
        </form>
        <form method="POST" action="{{ route('item-units.print-bulk') }}">@csrf
            <div class="overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-sm"><div class="flex items-center justify-between border-b border-gray-200 px-5 py-4"><p class="font-bold text-gray-900">Physical Inventory</p>@can('print item barcodes')<button class="rounded-xl bg-gray-900 px-4 py-2 text-sm font-semibold text-white">Print Selected</button>@endcan</div><div class="overflow-x-auto"><table class="min-w-full divide-y divide-gray-200"><thead class="bg-gray-50"><tr><th class="px-5 py-3"><input type="checkbox" onclick="document.querySelectorAll('.unit-check').forEach(e=>e.checked=this.checked)"></th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-500">Asset / Item</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-500">Serial / Property</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-500">Condition</th><th class="px-5 py-3 text-left text-xs font-bold uppercase text-gray-500">Availability</th><th class="px-5 py-3 text-right text-xs font-bold uppercase text-gray-500">Action</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($units as $unit)<tr class="hover:bg-gray-50"><td class="px-5 py-4"><input class="unit-check" type="checkbox" name="units[]" value="{{ $unit->id }}"></td><td class="px-5 py-4"><a href="{{ route('item-units.show',$unit) }}" class="font-bold text-green-700">{{ $unit->asset_number }}</a><p class="text-sm text-gray-600">{{ $unit->item->display_name }}</p></td><td class="px-5 py-4 text-sm"><p>{{ $unit->serial_number ?: 'No serial' }}</p><p class="text-gray-500">{{ $unit->property_number ?: 'No property no.' }}</p></td><td class="px-5 py-4"><span class="rounded-full bg-gray-100 px-3 py-1 text-xs font-semibold">{{ ucwords(str_replace('_',' ',$unit->condition)) }}</span></td><td class="px-5 py-4"><span class="rounded-full px-3 py-1 text-xs font-semibold {{ $unit->availability_status==='available'?'bg-green-100 text-green-700':'bg-amber-100 text-amber-700' }}">{{ ucfirst($unit->availability_status) }}</span></td><td class="px-5 py-4 text-right"><a href="{{ route('item-units.show',$unit) }}" class="font-semibold text-green-700">View</a></td></tr>@empty<tr><td colspan="6" class="px-5 py-14 text-center text-gray-500">No equipment units found.</td></tr>@endforelse</tbody></table></div></div>
        </form>
        {{ $units->links() }}
    </div>
</x-app-layout>
